### PR TITLE
Fixed 2 typos in the README and pumped dependencies and package versions

### PR DESCRIPTION
**Pull request by mo8it**
Passed all 8 tests!

### CODE REVIEW

**Comment by MasonProtter** [comment]
Awesome, this looks good thanks. I should actually remove the `Manifest.toml`, that shouldn't be here. I'm also going to re-setup the CI testing here and then I'll merge

**Comment by mo8it** [comment]
Thanks for the quick reply!
Yeah, it is kind of annoying that the package is holding updates back. Is this fixed by removing `Manifest.toml`?

**Comment by MasonProtter** [comment]
In this case, yes. Packages aren't supposed to include a `Manifest` unless they need exactly that specific combination of package versions to work right. I should have just had a `Project.toml` with some version bounds instead.

**Comment by MasonProtter** [comment]
Okay, looks like we're all good. Thank you!

**Comment by MasonProtter** [comment]
I have submitted a request for this new version to be in the general registry: https://github.com/JuliaRegistries/General/pull/44812 

Once that merges, you should be able `]add NaturallyUnitful` and not screw up your project with old versions.

**Pull request merged**
